version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mixer4422
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  server:
    build: ./backend/
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Mixer4422
      DB_NAME: numerdb
      DB_PORT: 3306

  app:
    build: ./numerproject/
    ports:
      - "3000:3000"
    depends_on:
      - server


